nelmio_api_doc:
    documentation:
        info:
            title: BileMo
            description: API de la socété BileMo
            version: 1.0.0
        servers:
            - url: https://127.0.0.1:8000
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
